apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-data-pvc
  labels:
    app: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
