apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pyspark-eda-custom
  labels:
    app: pyspark-eda
    component: custom-image
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pyspark-eda-custom:latest
  source:
    type: Git
    git:
      uri: https://github.com/ChWasam/spark_eda_k8s.git
      ref: main
    contextDir: eda
    sourceSecret:
      name: mygithub-secret # Replace with your actual secret name if needed
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
